### ISSUE TITLE
Unable to access url for marathon plugin interface

### ISSUE THREAD

**Issue by pmann91** [mesosphere/marathon-example-plugins#5]
I executed the "sbt clean package" for auth plugin but encountered the following error

*Server access Error: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target url=https://jcenter.bintray.com/mesosphere/marathon/plugin-interface_2.10/0.13.0/plugin-interface_2.10-0.13.0.pom*

Even tried to access the above url but got *404 could not find resource*

Even the http://downloads.mesosphere.io/maven throws Access denied error

**Comment by metskem** [comment]
I was also trying to get a plugin working, but need the plugin interface jar from http://downloads.mesosphere.io/maven, which fails.
The documented maven dependency does not resolve:
```xml
            <dependency>
            <groupId>mesosphere.marathon</groupId>
            <artifactId>plugin-interface</artifactId>
            <version></version>
        </dependency>
```
My IntelliJ only comes with this suggestion in pom.xml:

```xml
        <dependency>
            <groupId>mesosphere.marathon.example.plugin</groupId>
            <artifactId>marathon-example-plugins</artifactId>
            <version>1.1-SNAPSHOT</version>
        </dependency>
```

Any idea how to get the plugin interface jar?

**Comment by metskem** [comment]
As a temporary workaround you could build the marathon project (not the examples project) locally and get the classes from there.
For example:

    git clone git@github.com:mesosphere/marathon.git 
    cd marathon
    sbt assembly  
    # wait.....
    # jar up the plugin classes:
    cd plugin-interface/target/scala-2.11/classes 
    jar -cvf /tmp/mesosphere-marathon_plugin.jar *

**Comment by gkleiman** [comment]
Have you tried with version 0.13.0?

```xml
<dependency>
  <groupId>mesosphere.marathon</groupId>
  <artifactId>plugin-interface</artifactId>
  <version>0.13.0</version>
</dependency>
```

The jar is here: http://downloads.mesosphere.io/maven/mesosphere/marathon/plugin-interface_2.11/0.13.0/plugin-interface_2.11-0.13.0.jar

And here's the pom: https://downloads.mesosphere.io/maven/mesosphere/marathon/plugin-interface_2.11/0.13.0/plugin-interface_2.11-0.13.0.pom

**Comment by metskem** [comment]
Thanks, works fine for me. Closing the issue?
